"""Pitch database model — AI-generated WhatsApp pitch + sample posts."""

from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from nuhoot.database import Base


class Pitch(Base):
    """An AI-generated pitch for a business.

    Contains a personalized Arabic WhatsApp message and 3 sample Instagram
    post captions, generated by GLM 5.2 based on the business's digital
    presence investigation results.

    Status lifecycle: draft → approved → sent → failed
    """

    __tablename__ = "pitches"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    business_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    pitch_text: Mapped[str] = mapped_column(Text, nullable=False)
    sample_posts: Mapped[list[Any]] = mapped_column(JSON, insert_default=list)
    language: Mapped[str] = mapped_column(String(10), insert_default="ar")
    status: Mapped[str] = mapped_column(String(50), insert_default="draft")
    # draft → approved → sent → failed

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )

    def __init__(self, **kwargs: Any) -> None:
        kwargs.setdefault("language", "ar")
        kwargs.setdefault("status", "draft")
        kwargs.setdefault("sample_posts", [])
        super().__init__(**kwargs)
